name: Bug report
description: Report a bug in ivrobust
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal code or data to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Python version, OS, ivrobust version, and key dependencies.
  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste any relevant logs.
      render: shell
