name: Feature request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change you'd like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches or workarounds.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any references, papers, or examples.
